#!/bin/bash

PROVIDER=${1:-gcsfuse}
SCRIPT_DIR=${SCRIPTS_DIR:-"$(dirname "$(realpath "$0")")"}


if [[ -z "${G_BUCKET}" ]]; then
  echo "ERROR: G_BUCKET environment variable is not set."
  exit 1
fi

if [[ -z "${DATA_DIR}" ]]; then
  echo "ERROR: DATA_DIR environment variable is not set."
  exit 1
fi

if [[ ! -d "$DATA_DIR" ]]; then
    mkdir -p "$DATA_DIR"
fi

chmod g+w "$DATA_DIR"

# Service account credentials path
export CREDENTIALS_PATH="/tmp/sa.json"

# Check if service account file exists; if not, download it
if [[ ! -f "$CREDENTIALS_PATH" ]]; then
  echo "Service account file not found. Downloading..."
  # Get the directory of the current script
  "$SCRIPT_DIR"/fetch_service_acct.sh "$CREDENTIALS_PATH"
fi

# Run the appropriate initialization script based on the provider
case $PROVIDER in
  gcsfuse)
    "$SCRIPT_DIR"/init_gcsfuse.sh
    ;;
  
  rclone)
    "$SCRIPT_DIR"/init_rclone.sh
    ;;
  
  gcloud)
    "$SCRIPT_DIR"/init_gcloud.sh
    ;;
  
  *)
    echo "ERROR: Unknown provider $PROVIDER"
    exit 1
    ;;
esac

# Check exit status of the last command executed
if [[ $? -ne 0 ]]; then
  echo "ERROR: Initialization script for $PROVIDER failed."
  exit 1
fi

echo "Initialization for $PROVIDER completed successfully."