#!/bin/bash

if [[ -z "${GOOGLE_BUCKET_NAME}" ]]; then
  echo "ERROR: GOOGLE_BUCKET_NAME environment variable is not set."
  exit 1
fi

if [[ -z "${DATA_DIR}" ]]; then
  echo "ERROR: DATA_DIR environment variable is not set."
  exit 1
fi

# Check if the required environment variables are set
# Vast.ai only allows 256 characters in an environment variable
# Service account credentials are split into 12 environment variables as base64 encoded strings
for i in $(seq 1 12); do
  eval varr=\$GOOGLE_SERVICE_ACCT_CREDENTIALS_$i
  if [[ -z "$varr" ]]; then
    echo "ERROR: GOOGLE_SERVICE_ACCT_CREDENTIALS_$i environment variable is not set."
    exit 1
  fi
done

# Assemble the base64 string of service account credentials
GOOGLE_SERVICE_ACCT_CONTENTS=""
for i in $(seq 1 12); do
  eval varr=\$GOOGLE_SERVICE_ACCT_CREDENTIALS_$i
  GOOGLE_SERVICE_ACCT_CONTENTS+="$varr"
done

# Servie account credentials path
CREDENTIALS_PATH="/tmp/service_account.json"

# Decode and save to a JSON file
echo "$GOOGLE_SERVICE_ACCT_CONTENTS" | base64 -d > $CREDENTIALS_PATH

# Mount path
MOUNT_PATH=$DATA_DIR

# Create Dir
mkdir -p $MOUNT_PATH

# Give permission to group
chmod g+w $MOUNT_PATH



# Initialize gcloud with service account
gcloud auth activate-service-account --key-file=$CREDENTIALS_PATH

# Mount the bucket
mkdir -p $MOUNT_PATH
gcsfuse --key-file=$CREDENTIALS_PATH $GOOGLE_BUCKET_NAME $MOUNT_PATH

# Clean up the credentials file
rm $CREDENTIALS_PATH

# Verify mounting
if mount | grep "gcsfuse" > /dev/null; then
  echo "Bucket mounted successfully at $MOUNT_PATH"
else
  echo "ERROR: Bucket mounting failed."
  exit 1
fi
