#!/bin/bash

# Installing Rclone

sudo apt-get update && sudo apt-get install -y unzip

echo "Installing Rclone..."
sudo -v ; curl -sS https://rclone.org/install.sh | sudo bash

# Verify installation
echo "Verifying installations..."
if command -v rclone &> /dev/null; then
    echo "Installation complete: Rclone is now installed."
else
    echo "Error: Installation failed for Rclone"
    exit 1
fi
